# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"\x1c\n\x08img_path\x12\x10\n\x08img_path\x18\x01 \x01(\t\"+\n\x05image\x12\x13\n\x0bimg_content\x18\x01 \x01(\x0c\x12\r\n\x05\x64type\x18\x02 \x01(\t\"K\n\nprediction\x12\x1b\n\x0bpred_imagen\x18\x01 \x01(\x0b\x32\x06.image\x12\x12\n\npercentage\x18\x02 \x01(\x02\x12\x0c\n\x04type\x18\x03 \x01(\t26\n\tInference\x12)\n\rrun_inference\x12\t.img_path\x1a\x0b.prediction\"\x00\x62\x06proto3')



_IMG_PATH = DESCRIPTOR.message_types_by_name['img_path']
_IMAGE = DESCRIPTOR.message_types_by_name['image']
_PREDICTION = DESCRIPTOR.message_types_by_name['prediction']
img_path = _reflection.GeneratedProtocolMessageType('img_path', (_message.Message,), {
  'DESCRIPTOR' : _IMG_PATH,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:img_path)
  })
_sym_db.RegisterMessage(img_path)

image = _reflection.GeneratedProtocolMessageType('image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:image)
  })
_sym_db.RegisterMessage(image)

prediction = _reflection.GeneratedProtocolMessageType('prediction', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:prediction)
  })
_sym_db.RegisterMessage(prediction)

_INFERENCE = DESCRIPTOR.services_by_name['Inference']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMG_PATH._serialized_start=19
  _IMG_PATH._serialized_end=47
  _IMAGE._serialized_start=49
  _IMAGE._serialized_end=92
  _PREDICTION._serialized_start=94
  _PREDICTION._serialized_end=169
  _INFERENCE._serialized_start=171
  _INFERENCE._serialized_end=225
# @@protoc_insertion_point(module_scope)
