# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import db_access_pb2 as db__access__pb2


class DBAccessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.store_patient = channel.unary_unary(
                '/DBAccess/store_patient',
                request_serializer=db__access__pb2.patient_data.SerializeToString,
                response_deserializer=db__access__pb2.store_status.FromString,
                )
        self.load_patient = channel.unary_unary(
                '/DBAccess/load_patient',
                request_serializer=db__access__pb2.patient_id.SerializeToString,
                response_deserializer=db__access__pb2.patient_data.FromString,
                )


class DBAccessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def store_patient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load_patient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBAccessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'store_patient': grpc.unary_unary_rpc_method_handler(
                    servicer.store_patient,
                    request_deserializer=db__access__pb2.patient_data.FromString,
                    response_serializer=db__access__pb2.store_status.SerializeToString,
            ),
            'load_patient': grpc.unary_unary_rpc_method_handler(
                    servicer.load_patient,
                    request_deserializer=db__access__pb2.patient_id.FromString,
                    response_serializer=db__access__pb2.patient_data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DBAccess', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DBAccess(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def store_patient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBAccess/store_patient',
            db__access__pb2.patient_data.SerializeToString,
            db__access__pb2.store_status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def load_patient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBAccess/load_patient',
            db__access__pb2.patient_id.SerializeToString,
            db__access__pb2.patient_data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
