# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db_access.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x62_access.proto\"\xa9\x01\n\x0cpatient_data\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0f\n\x07id_type\x18\x03 \x01(\t\x12\x0e\n\x06id_num\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12\x10\n\x08img_path\x18\x06 \x01(\t\x12\x13\n\x0bpred_imagen\x18\x07 \x01(\x0c\x12\x12\n\npercentage\x18\x08 \x01(\x02\x12\x0c\n\x04type\x18\t \x01(\t\"\x1f\n\x0cstore_status\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\npatient_id\x12\x0e\n\x06id_num\x18\x01 \x01(\t2i\n\x08\x44\x42\x41\x63\x63\x65ss\x12/\n\rstore_patient\x12\r.patient_data\x1a\r.store_status\"\x00\x12,\n\x0cload_patient\x12\x0b.patient_id\x1a\r.patient_data\"\x00\x62\x06proto3')



_PATIENT_DATA = DESCRIPTOR.message_types_by_name['patient_data']
_STORE_STATUS = DESCRIPTOR.message_types_by_name['store_status']
_PATIENT_ID = DESCRIPTOR.message_types_by_name['patient_id']
patient_data = _reflection.GeneratedProtocolMessageType('patient_data', (_message.Message,), {
  'DESCRIPTOR' : _PATIENT_DATA,
  '__module__' : 'db_access_pb2'
  # @@protoc_insertion_point(class_scope:patient_data)
  })
_sym_db.RegisterMessage(patient_data)

store_status = _reflection.GeneratedProtocolMessageType('store_status', (_message.Message,), {
  'DESCRIPTOR' : _STORE_STATUS,
  '__module__' : 'db_access_pb2'
  # @@protoc_insertion_point(class_scope:store_status)
  })
_sym_db.RegisterMessage(store_status)

patient_id = _reflection.GeneratedProtocolMessageType('patient_id', (_message.Message,), {
  'DESCRIPTOR' : _PATIENT_ID,
  '__module__' : 'db_access_pb2'
  # @@protoc_insertion_point(class_scope:patient_id)
  })
_sym_db.RegisterMessage(patient_id)

_DBACCESS = DESCRIPTOR.services_by_name['DBAccess']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PATIENT_DATA._serialized_start=20
  _PATIENT_DATA._serialized_end=189
  _STORE_STATUS._serialized_start=191
  _STORE_STATUS._serialized_end=222
  _PATIENT_ID._serialized_start=224
  _PATIENT_ID._serialized_end=252
  _DBACCESS._serialized_start=254
  _DBACCESS._serialized_end=359
# @@protoc_insertion_point(module_scope)
